In [1]:
#Please execute this cell
import jupman

# Matrices: Numpy 1 

## [Download exercises zip](../_static/generated/matrices-numpy.zip)

[Browse files online](https://github.com/DavidLeoni/softpython-en/tree/master/matrices-numpy)


## Introduction


Previously we've seen [Matrices as lists of lists](https://en.softpython.org/matrices-lists/matrices-lists-sol.html), here we focus on matrices using Numpy library

There are substantially two ways to represent matrices in Python: as list of lists, or with the external library [numpy](https://www.numpy.org). The most used is surely Numpy, let's see the reason the principal differences:

List of lists - [see separate notebook](https://en.softpython.org/matrices-lists/matrices-lists1-sol.html)

1. native in Python
2. not efficient
3. lists are pervasive in Python, probably you will encounter matrices expressed as list of lists anyway
4. give an idea of how to build a nested data structure
5. may help in understanding important concepts like pointers to memory and copies

Numpy - this notebook

1. not natively available  in Python
2. efficient
3. many libraries for scientific calculations are based on Numpy (scipy, pandas)
4. syntax to access elements is slightly different from list of lists
5. in rare cases might give problems of installation and/or conflicts (implementation is not pure Python)

Here we will see data types and essential commands of [Numpy library](https://www.numpy.org), but we will not get into the details.

The idea is to simply pass using the the data format `ndarray` without caring too much about performances: for example, even if `for` cycles in Python are slow because they operate cell by cell, we will use them anyway. In case you actually need to execute calculations fast, you will want to use operators on vectors but for this we invite you to read links below

<div class="alert alert-warning">

**ATTENTION**: Numpy does not work in [Python Tutor](http://www.pythontutor.com/visualize.html#mode=edit)
    
</div>

### What to do

- unzip exercises in a folder, you should get something like this: 

```
matrices-numpy
    matrices-numpy1.ipynb
    matrices-numpy1-sol.ipynb
    matrices-numpy2.ipynb
    matrices-numpy2-sol.ipynb
    matrices-numpy3-chal.ipynb
    numpy-images.ipynb
    numpy-images-sol.ipynb    
    jupman.py
```

<div class="alert alert-warning">

**WARNING**: to correctly visualize the notebook, it MUST be in an unzipped folder !
</div>


- open Jupyter Notebook from that folder. Two things should open, first a console and then browser. The browser should show a file list: navigate the list and open the notebook `matrices-numpy/matrices-numpy1.ipynb`
- Go on reading that notebook, and follow instuctions inside.


Shortcut keys:

- to execute Python code inside a Jupyter cell, press `Control + Enter`
- to execute Python code inside a Jupyter cell AND select next cell, press `Shift + Enter`
- to execute Python code inside a Jupyter cell AND a create a new cell aftwerwards, press `Alt + Enter`
- If the notebooks look stuck, try to select `Kernel -> Restart`

## np.array

First of all, we import the library, and for convenience we rename it to `np`

In [2]:
import numpy as np


With lists of lists we have often built the matrices one row at a time, adding lists as needed. In Numpy instead we usually create in one shot the whole matrix, filling it with zeroes.

In particular, this command creates an `ndarray` filled with zeroes:

In [3]:
mat = np.zeros( (2,3)  )   # 2 rows, 3 columns

In [4]:
mat

array([[0., 0., 0.],
       [0., 0., 0.]])

Note like inside `array( )` the content seems represented like a list of lists, BUT in reality in physical memory the data is structured in a linear sequence which allows Python to access numbers in a faster way.

We can also create an `ndarray` from a list of lists:

In [5]:
mat = np.array( [ [5.0,8.0,1.0], 
                  [4.0,3.0,2.0]])

In [6]:
mat

array([[5., 8., 1.],
       [4., 3., 2.]])

In [7]:
type(mat)

numpy.ndarray

## Creating a matrix filled with ones

In [8]:
np.ones((3,5))  # 3 rows, 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Creating a matrix filled with a number `k`

In [9]:
np.full((3,5), 7)   

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

## Dimensions of a matrix

To obtain the dimension, we write like the following:

    
<div class="alert alert-warning">

**ATTENTION**: after `shape` there are **no** round parenthesis !

`shape` is an attribute, not a function to call
</div>

In [10]:
mat = np.array( [ [5.0,8.0,1.0], 
                  [4.0,3.0,2.0]])

mat.shape

(2, 3)


If we want to memorize the dimension in separate variables, we can use thi more pythonic mode (note the comma between `num_rows` and `num_cols`:

In [11]:
num_rows, num_cols = mat.shape

In [12]:
num_rows

2

In [13]:
num_cols

3

## Reading and writing

To access data or overwrite square bracket notation is used, with the important difference that in Numpy you can write _both_ the indeces _inside_ the same brackets, separated by a comma:


<div class="alert alert-warning">

**ATTENTION**: notation `mat[i,j]` is only for Numpy, with list of lists **does not** work!
</div>

In [14]:
mat = np.array( [ [5.0,8.0,1.0], 
                  [4.0,3.0,2.0]])

# Let's put number `9` in cell at row `0` and column `1`

mat[0,1] = 9

In [15]:
mat

array([[5., 9., 1.],
       [4., 3., 2.]])

Let's access cell at row `0` and column `1`

In [16]:
mat[0,1]

9.0

We put number `7` into cell at row `1` and column `2`

In [17]:
mat[1,2] = 7

In [18]:
mat

array([[5., 9., 1.],
       [4., 3., 7.]])

**✪ EXERCISE**: try to write like the following, what happens? 

```python
mat[0,0] = "c"
```

In [19]:
# write here



**✪ EXERCISE**: Try writing like this, what happens?
    
```python
mat[1,1.0]
```

In [20]:
# write here



### Filling the whole matrix

We can MODIFY the matrix by writing inside a number with  `fill()`

In [21]:
mat = np.array([[3.0, 5.0, 2.0],
                [6.0, 2.0, 9.0]])

mat.fill(7)  # NOTE: returns nothings !!

In [22]:
mat

array([[7., 7., 7.],
       [7., 7., 7.]])

### Slices

To extract data from an `ndarray` we can use slices, with the notation we already used for regular lists. There are important difference, though. Let's see them.

The first difference is that we can extract sub-matrices by specifying two ranges among the same squared brackets:

In [23]:
mat = np.array( [ [5, 8, 1], 
                  [4, 3, 2],
                  [6, 7, 9],
                  [9, 3, 4],
                  [8, 2, 7]])

In [24]:
mat[0:4, 1:3]  # rows from 0 *included* to 4 *excluded*
               # and columns from 1 *included* to 3 *excluded*
               

array([[8, 1],
       [3, 2],
       [7, 9],
       [3, 4]])

In [25]:
mat[0:1,0:3]  # the whole first row

array([[5, 8, 1]])

In [26]:
mat[0:1,:]  # another way to extract the whole first row

array([[5, 8, 1]])

In [27]:
mat[0:5, 0:1]  # the whole first column

array([[5],
       [4],
       [6],
       [9],
       [8]])

In [28]:
mat[:, 0:1]  # another way to extract the whole first column

array([[5],
       [4],
       [6],
       [9],
       [8]])

**The step**: We can also specify a step as a third paramter after the `:`. For example, to extract only even rows we can add a `2` like this:

In [29]:
mat[0:5:2, :]

array([[5, 8, 1],
       [6, 7, 9],
       [8, 2, 7]])

<div class="alert alert-warning">
    
**WARNING: by modifying the numpy slice you also modify the original matrix!**

</div>   

Differently from slices of lists which always produce new lists, this time of performance reasons with numpy slices we only obtain a _view_ on the original data: by writing into the view we will also write on the original matrix:

In [30]:
mat = np.array( [ [5, 8, 1], 
                  [4, 3, 2],
                  [6, 7, 9],
                  [9, 3, 4],
                  [8, 2, 7]])

In [31]:
sub_mat = mat[0:4, 1:3]  
sub_mat

array([[8, 1],
       [3, 2],
       [7, 9],
       [3, 4]])

In [32]:
sub_mat[0,0] = 999

In [33]:
mat

array([[  5, 999,   1],
       [  4,   3,   2],
       [  6,   7,   9],
       [  9,   3,   4],
       [  8,   2,   7]])

### Writing a constant in a slice

We can also write a constant in all the cells of a region by identifying the region with a slice, and assigning a constant to it:

In [34]:
mat = np.array( [ [5, 8, 1], 
                  [4, 3, 2],
                  [6, 7, 9],
                  [9, 3, 4],
                  [8, 2, 5]])

mat[0:4, 1:3]  = 7

mat

array([[5, 7, 7],
       [4, 7, 7],
       [6, 7, 7],
       [9, 7, 7],
       [8, 2, 5]])

### Writing a matrix into a slice

We can also write into all the cells in a region by identifying the region with a slice, and then assigning to it a matrix from which we want to read the cells.


**WARNING**: To avoid problems, **double check** you're using the same dimensions in both left and right slices!

In [35]:
mat = np.array( [ [5, 8, 1], 
                  [4, 3, 2],
                  [6, 7, 9],
                  [9, 3, 4],
                  [8, 2, 5]])

mat[0:4, 1:3]  = np.array([
                            [10,50],
                            [11,51],
                            [12,52],
                            [13,53],
                        ])

mat

array([[ 5, 10, 50],
       [ 4, 11, 51],
       [ 6, 12, 52],
       [ 9, 13, 53],
       [ 8,  2,  5]])

## Assignment and copy

With Numpy we must take particular care when using the assignment operator `=`: as with regular lists, if we perform an assignment into the new variable, it will only contain a pointer to the original region of memory.

In [36]:
va = np.array([1,2,3])

In [37]:
va

array([1, 2, 3])

In [38]:
vb = va

In [39]:
vb[0] = 100

In [40]:
vb

array([100,   2,   3])

In [41]:
va

array([100,   2,   3])

If we wanted a complete copy of the array, we should use the `.copy()` method:

In [42]:
va = np.array([1,2,3])

In [43]:
vc = va.copy()

In [44]:
vc

array([1, 2, 3])

In [45]:
vc[0] = 100

In [46]:
vc

array([100,   2,   3])

In [47]:
va

array([1, 2, 3])

## Calculations

Numpy is extremely flexible, and allows us to perform on arrays almost the same operations from classical vector and matrix algebra:

In [48]:
va = np.array([5,9,7]) 
va

array([5, 9, 7])

In [49]:
vb = np.array([6,8,0]) 
vb

array([6, 8, 0])

Whenever we perform an algebraic operation, typically a NEW array is created:


In [50]:
vc = va + vb   
vc

array([11, 17,  7])

Note the sum didn't change the input:

In [51]:
va

array([5, 9, 7])

In [52]:
vb

array([6, 8, 0])

### Scalar multiplication

In [53]:
m = np.array([[5, 9, 7],
              [6, 8, 0]])

In [54]:
3 * m

array([[15, 27, 21],
       [18, 24,  0]])

### Scalar sum

In [55]:
3 + m

array([[ 8, 12, 10],
       [ 9, 11,  3]])

### Multiplication

Be careful about multiplying with `*`: differently from classical matrix multiplication, it multiplies _element by element_ and so requires matrices of identical dimensions:

In [56]:
ma = np.array([[1,  2,  3],
               [10, 20, 30]])

mb = np.array([[1,  0,  1],
               [4,  5,  6]]) 

ma * mb

array([[  1,   0,   3],
       [ 40, 100, 180]])

If we want the matrix multiplication [from classical algebra](https://en.wikipedia.org/wiki/Matrix_multiplication), we must use the `@` operator taking care of having compatible matrix dimensions:

In [57]:
mc = np.array([[1,  2,  3],
               [10, 20, 30]])
md = np.array([[1, 4],
               [0, 5],
               [1, 6]]) 

mc @ md

array([[  4,  32],
       [ 40, 320]])

### Dividing by a scalar

In [58]:
ma = np.array([[1,  2,  0.0],
               [10, 0.0, 30]])

ma / 4

array([[0.25, 0.5 , 0.  ],
       [2.5 , 0.  , 7.5 ]])

Careful about dividing by `0.0`, the program execution will still continue with a warning and we will find a matrix with strange `nan` and `inf` which have a bad tendency to create problems later - see the section [NaNs and infinities](#NaNs-and-infinities)

In [59]:
print(ma / 0.0)
print("AFTER")

[[inf inf nan]
 [inf nan inf]]
AFTER


/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


## Aggregation

Numpy provides several functions to calculate statistics, we only show some:

In [60]:
m = np.array([[5, 4, 6],
              [3, 7, 1]])
np.sum(m)

26

In [61]:
np.max(m)   

7

In [62]:
np.min(m)

1

### Aggregating by row or column

By adding the `axis` parameter we can tell numpy to perform the affrefation on each column (`axis=0`) or row (`axis=1`):

In [63]:
np.max(m, axis=0)  # the maximum of each column

array([5, 7, 6])

In [64]:
np.sum(m, axis=0)   # sum each column

array([ 8, 11,  7])

In [65]:
np.max(m, axis=1)  # the maximum of each row

array([6, 7])

In [66]:
np.sum(m, axis=1)   # sum each row

array([15, 11])

## Filtering

Numpy offers a mini-language to filter the numbers in an array, by specifying the selection criteria. Let's see an example:

In [67]:
mat = np.array([[5, 2, 6],
                [1, 4, 3]])
mat

array([[5, 2, 6],
       [1, 4, 3]])

Suppose you want to obtain an array with all the numbers from `mat` which are greater than 2.

We can tell numpy the matrix `mat` we want to use, then _inside square brackets_ we put a kind of boolean conditions, _reusing_ the `mat` variable like so:

In [68]:
mat[ mat > 2 ]

array([5, 6, 4, 3])

Exactly, what is that strange expression we put inside the squared brackts? Let's try executing it alone:

In [69]:
mat > 2

array([[ True, False,  True],
       [False,  True,  True]])

We note it gives us a matrix of booleans, which are `True` whenever the corresponding cell in the original matrix satisfies the condition we imposed.

By then placing this expression inside `mat[   ]` we obtain the values from the original matrix which satisfy the expression:

In [70]:
mat[ mat > 2 ]

array([5, 6, 4, 3])

Not only that, we can also build more complex expressions by using 

* `&` symbol as the logical conjunction _and_
* `|` (pipe character) as the logical conjunction _or_

In [71]:
mat = np.array([[5, 2, 6],
                [1, 4, 3]])
mat[(mat > 3) & (mat < 6)]

array([5, 4])

In [72]:
mat = np.array([[5, 2, 6],
                [1, 4, 3]])
mat[(mat < 2) | (mat > 4)]

array([5, 6, 1])

<div class="alert alert-warning">

**WARNING: REMEMBER THE ROUND PARENTHESIS AMONG THE VARIOUS EXPRESSIONS!**  
</div>

**EXERCISE**: try to rewrite the expressions above by 'forgetting' the round parenthesis in the various components (left/right/both) and see what happens. Do you obtain errors or unexpected results?

In [73]:

mat = np.array([[5, 2, 6],
                [1, 4, 3]])

# write here
print(  mat[(mat > 3) & mat < 6]  )
print(  mat[mat > 3 & (mat < 6)]    )
#print(  mat[mat > 3 & mat < 6]      )
# the last one produces:
# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-212-33c5a083b265> in <module>
#       3 print(  mat[(mat > 3) & mat < 6]  )
#       4 print(  mat[mat > 3 & (mat < 6)]    )
# ----> 5 print(  mat[mat > 3 & mat < 6]      )

# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[5 2 6 1 4 3]
[5 2 6 4 3]


In [73]:

mat = np.array([[5, 2, 6],
                [1, 4, 3]])

# write here



<div class="alert alert-warning">

**WARNING**:  `and` **and** `or` **DON'T WORK!**
</div>

**EXERCISE**: try rewriting the expressions above by substituting `&` with `and` and `|` with `or` and see what happens. Do you get errors or unexpected results?

In [74]:

mat = np.array([[5, 2, 6],
                [1, 4, 3]])

# write here
#print(  mat[(mat > 3) and (mat < 6) ]  )
#---------------------------------------------------------------------------
#ValueError                                Traceback (most recent call last)
#<ipython-input-218-3edf025af7c0> in <module>
#      4 
#      5 # write here
#----> 6 print(  mat[(mat > 3) and (mat < 6) ]  )     

#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#print(  mat[(mat > 3) or (mat < 6)]    )
#---------------------------------------------------------------------------
#ValueError                                Traceback (most recent call last)
#<ipython-input-219-192c022d9d87> in <module>
#     16 
#     17 
#---> 18 print(  mat[(mat > 3) or (mat < 6)]    )

#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:

mat = np.array([[5, 2, 6],
                [1, 4, 3]])

# write here



### Finding indexes with  `np.where`

We've seen how to find the content of cells which satisfy a certain criteria.   What if we wanted to find the _indeces_ of those cells? In that case we would use the function `np.where`, passing as parameter the condition expressed in the same language used before.

For example, if we wanted to find the _indexes_ of cells containing numbers less than 40 or greater than 60 we would write like so:

In [75]:
             #0  1  2  3  4  5
v = np.array([30,60,20,70,40,80])

np.where((v < 40) | (v > 60))

(array([0, 2, 3, 5]),)

### Writing into cells which satisfy a criteria

We can use `np.where` to substitute values in the cells which satisfy a criteria with other values which we'll be expressed in two extra matrices `ma` and `mb`. In case the criteria is satisfied, numpy will take the corresponding values from `ma`, otherwise from `mb`.

In [76]:
ma = np.array([
    [ 1, 2, 3, 4],
    [ 5, 6, 7, 8],
    [ 9,10,11,12]
])

mb = np.array([
    [ -1, -2, -3, -4],
    [ -5, -6, -7, -8],
    [ -9,-10,-11,-12]
])


mat = np.array([
    [40,70,10,80],
    [20,30,60,40],
    [10,60,80,90]
])

np.where(mat < 50, ma, mb) 

array([[  1,  -2,   3,  -4],
       [  5,   6,  -7,   8],
       [  9, -10, -11, -12]])

## arange and linspace sequences

The standard function `range` of Python does not allow for float increments, which we can instead obtain by building sequences of float numbers with `np.arange`, by specifying left limit (**included**), right limit (**excluded**) and the increment: 

In [77]:
np.arange(0.0, 1.0, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

Alternatively, we can use `np.linspace`, which takes a left limit **included**, a right limit this time **included**, and the **number of repetitions** to subdivide this space:

In [78]:
np.linspace(0, 0.8, 5)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [79]:
np.linspace(0, 0.8, 10)

array([0.        , 0.08888889, 0.17777778, 0.26666667, 0.35555556,
       0.44444444, 0.53333333, 0.62222222, 0.71111111, 0.8       ])

## NaNs and infinities


Float numbers can be numbers and.... not numbers, and infinities. Sometimes during calculations extremal conditions may arise, like when dividing a small number by a huge number. In such cases, you might end up having a float which is a dreaded _Not a Number_, _NaN_ for short, or you might get an infinity. This can lead to very awful unexpected behaviours, so you must be well aware of it. 

Following behaviours are dictated by IEEE Standard for Binary Floating-Point for Arithmetic (IEEE 754) which Numpy uses and is implemented in all CPUs, so they actually  regard all programming languages. 

### NaNs

A NaN is _Not a Number_. Which is already a silly name, since a NaN is actually a very special member of floats, with this astonishing property:

<div class="alert alert-warning">

**WARNING: NaN IS NOT EQUAL TO ITSELF** !!!! 

Yes you read it right, NaN is really _not_ equal to itself.
</div>

Even if your mind wants to refuse it, we are going to confirm it.

To get a NaN, you can use Python module `math` which holds this alien item: 

In [80]:
import math
math.nan    # notice it prints as 'nan' with lowercase n

nan

As we said, a NaN is actually considered a float:

In [81]:
type(math.nan)

float

Still, it behaves very differently from its fellow floats, or any other object in the known universe:

In [82]:
math.nan == math.nan   # what the F... alse

False

### Detecting NaN

Given the above, if you want to check if a variable `x` is a NaN, you _cannot_ write this: 

In [83]:
x = math.nan
if x == math.nan:  # WRONG
    print("I'm NaN ")
else:
    print("x is something else ??")

x is something else ??


To correctly handle this situation, you need to use `math.isnan` function:

In [84]:
x = math.nan
if math.isnan(x):  # CORRECT
    print("x is NaN ")
else:
    print("x is something else ??")

x is NaN 


Notice `math.isnan` also work with _negative_ NaN:

In [85]:
y = -math.nan
if math.isnan(y):  # CORRECT
    print("y is NaN ")
else:
    print("y is something else ??")

y is NaN 


### Sequences with NaNs

Still, not everything is completely crazy. If you compare a sequence holding NaNs to another one, you will get reasonable results:

In [86]:
[math.nan, math.nan] == [math.nan, math.nan]

True

### Exercise NaN: two vars

Given two number variables `x` and `y`, write some code that prints `"same"` when they are the same, _even_ when they are NaN. Otherwise, prints `"not the same"

In [87]:
# expected output: same
x = math.nan
y = math.nan

# expected output: not the same
#x = 3
#y = math.nan

# expected output: not the same
#x = math.nan
#y = 5

# expected output: not the same
#x = 2
#y = 7

# expected output: same
#x = 4
#y = 4

# write here
if math.isnan(x) and math.isnan(y):
    print('same')
elif x == y:
    print('same')
else:
    print('not the same')

same


In [87]:
# expected output: same
x = math.nan
y = math.nan

# expected output: not the same
#x = 3
#y = math.nan

# expected output: not the same
#x = math.nan
#y = 5

# expected output: not the same
#x = 2
#y = 7

# expected output: same
#x = 4
#y = 4

# write here



same


### Operations on NaNs

Any operation on a NaN will generate another NaN:

In [88]:
5 * math.nan

nan

In [89]:
math.nan + math.nan

nan

In [90]:
math.nan / math.nan

nan

The only thing you cannot do is dividing by zero with an unboxed NaN:

```python
math.nan / 0
```

```python
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-94-1da38377fac4> in <module>
----> 1 math.nan / 0

ZeroDivisionError: float division by zero
```

NaN corresponds to boolean value `True`:

In [91]:
if math.nan: 
    print("That's True")

That's True


### NaN and Numpy

When using Numpy you are quite likely to encounter NaNs, so much so they get redefined inside Numpy, but they are exactly the same as in `math` module:

In [92]:
np.nan

nan

In [93]:
math.isnan(np.nan)

True

In [94]:
np.isnan(math.nan)

True

In Numpy when you have unknown numbers you might be tempted to put a `None`. You can actually do it, but look closely at the result:

In [95]:
import numpy as np
np.array([4.9,None,3.2,5.1])

array([4.9, None, 3.2, 5.1], dtype=object)

The resulting array type is _not_  an array of float64 which allows fast calculations, instead it is an array containing generic _objects_, as Numpy is assuming the array holds heterogenous data. So what you gain in generality you lose it in performance, which should actually be the whole point of using Numpy. 

Despite being weird, NaNs are actually regular float citizen so they can be stored in the array:

In [96]:
np.array([4.9,np.nan,3.2,5.1])   # Notice how the `dtype=object` has disappeared

array([4.9, nan, 3.2, 5.1])

### Where are the NaNs ?

Let's try to see where we can spot NaNs and other weird things such infinities in the wild

First, let check what happens when we call function `log` of standard module `math`.
As we know, log function behaves like this:

* $x < 0$: not defined 
* $x = 0$: tends to minus infinity 
* $x > 0$: defined

![log function u9u9u9](_static/img/log.png)

So we might wonder what happens when we pass to it a value where it is not defined. Let's first try with the standard `math.log`  from Python library:

```python
>>> math.log(-1)
```
```python
ValueError                                Traceback (most recent call last)
<ipython-input-38-d6e02ba32da6> in <module>
----> 1 math.log(-1)

ValueError: math domain error
```

In this case `ValueError` is raised and **the execution gets interrupted.**

Let's try the equivalent with Numpy:

In [97]:
np.log(-1)

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In this case we **actually got as a result** `np.nan`, so execution was not interrupted, Jupyter only informed us with an extra print that something dangerous happened.

The default behaviour of Numpy regarding dangerous calculations is to perform them anyway and storing the result in as a NaN or other limit objects. This also works for arrays calculations:

In [98]:
np.log(np.array([3,7,-1,9]))

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([1.09861229, 1.94591015,        nan, 2.19722458])

### Infinities

As we said previously, NumPy uses the IEEE Standard for Binary Floating-Point for Arithmetic (IEEE 754). Since somebody at IEEE decided to capture the misteries of infinity into floating numbers, we have yet another citizen to take into account when performing calculations (for more info see [Numpy documentation on constants](https://numpy.org/devdocs/reference/constants.html)):

### Positive infinity `np.inf`

In [99]:
 np.array( [ 5 ] ) / 0

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf])

In [100]:
np.array( [ 6,9,5,7 ] ) / np.array( [ 2,0,0,4 ] )

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([3.  ,  inf,  inf, 1.75])

Be aware that: 

- Not a Number is **not** equivalent to infinity
- positive infinity is **not** equivalent to negative infinity
- infinity is equivalent to positive infinity

This time, infinity is equal to infinity: 

In [101]:
np.inf == np.inf

True

so we can safely detect infinity with `==`:

In [102]:
x = np.inf
 
if x == np.inf:
    print("x is infinite")
else:
    print("x is finite")

x is infinite


Alternatively, we can use the function `np.isinf`: 

In [103]:
np.isinf(np.inf)

True

### Negative infinity

We can also have negative infinity, which is different from positive infinity:

In [104]:
-np.inf == np.inf

False

Note that `isinf` detects _both_ positive and negative:

In [105]:
np.isinf(-np.inf)

True

To actually check for negative infinity you have to use `isneginf`:

In [106]:
np.isneginf(-np.inf)

True

In [107]:
np.isneginf(np.inf)

False

Where do they appear? As an example, let's try `np.log` function:

In [108]:
np.log(0)

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

### Combining infinities and NaNs

When performing operations involving infinities and NaNs, IEEE arithmetics tries to mimic classical analysis, sometimes including NaN as a result:

In [109]:
np.inf + np.inf

inf

In [110]:
- np.inf - np.inf

-inf

In [111]:
np.inf * -np.inf

-inf

What in classical analysis would be undefined, here becomes NaN: 

In [112]:
np.inf - np.inf

nan

In [113]:
np.inf / np.inf

nan

As usual, combining with NaN results in NaN:

In [114]:
np.inf + np.nan

nan

In [115]:
np.inf / np.nan

nan

### Negative zero 

We can even have a _negative_ zero - who would have thought?

In [116]:
np.NZERO

-0.0

Negative zero of course pairs well with the more known and much appreciated _positive_ zero:

In [117]:
np.PZERO

0.0

**NOTE**: Writing `np.NZERO` or `-0.0` is _exactly_ the same thing. Same goes for positive zero.

At this point, you might start wondering with some concern if they are actually _equal_. Let's try:

In [118]:
0.0 == -0.0

True

Great! Finally one thing that makes sense. 

Given the above, you might think in a formula you can substitute one for the other one and get same results, in harmony with the rules of the universe. 

Let's make an attempt of substitution, as an example we first try dividing a number by positive zero (even if math teachers tell us such divisions are forbidden) - what will we ever get??

$\frac{5.0}{0.0}=???$

In Numpy terms, we might write like this to box everything in arrays:

In [119]:
np.array( [ 5.0 ] ) / np.array( [ 0.0 ] )

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf])

Hmm, we got an array holding an `np.inf`.

If `0.0`  and `-0.0` are actually the same, dividing a number by `-0.0`  we should get the very same result, shouldn't we?

Let's try:

In [120]:
np.array( [ 5.0 ] ) / np.array( [ -0.0 ] )

/home/da/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-inf])

Oh gosh. This time we got an array holding a _negative_ infinity `-np.inf`

If all of this seems odd to you, do not bash at Numpy. This is the way pretty much any CPUs does floating point calculations so you will find it in almost ALL computer languages.

What programming languages can do is add further controls to protect you from paradoxical situations, for example when you directly write `1.0/0.0` Python raises `ZeroDivisionError` (blocking thus execution), and when you operate on arrays Numpy emits a warning (but doesn't block execution).

### Exercise: detect proper numbers

Write some code that PRINTS `equal numbers` if two numbers `x` and `y` passed are equal and actual numbers, and PRINTS `not equal numbers` otherwise. 

**NOTE**: `not equal numbers` must be printed if any of the numbers is infinite or NaN.

To solve it, feel free to call functions indicated in [Numpy documentation about costants](https://docs.scipy.org/doc/numpy/reference/constants.html)

In [121]:
# expected: equal numbers
x = 5
y = 5

# expected: not equal numbers
#x = np.inf
#y = 3

# expected: not equal numbers
#x = 3
#y = np.inf

# expected: not equal numbers
#x = np.inf
#y = np.nan

# expected: not equal numbers
#x = np.nan
#y = np.inf

# expected: not equal numbers
#x = np.nan
#y = 7

# expected: not equal numbers
#x = 9
#y = np.nan

# expected: not equal numbers
#x = np.nan
#y = np.nan


# write here

# SOLUTION 1 - the ugly one
if np.isinf(x) or np.isinf(y) or np.isnan(x) or np.isnan(y):
    print('not equal numbers')
else:
    print('equal numbers')
    
# SOLUTION 2 - the pretty one
if np.isfinite(x) and np.isfinite(y):
    print('equal numbers')
else:
    print('not equal numbers')

equal numbers
equal numbers


In [121]:
# expected: equal numbers
x = 5
y = 5

# expected: not equal numbers
#x = np.inf
#y = 3

# expected: not equal numbers
#x = 3
#y = np.inf

# expected: not equal numbers
#x = np.inf
#y = np.nan

# expected: not equal numbers
#x = np.nan
#y = np.inf

# expected: not equal numbers
#x = np.nan
#y = 7

# expected: not equal numbers
#x = 9
#y = np.nan

# expected: not equal numbers
#x = np.nan
#y = np.nan


# write here



equal numbers
equal numbers


### Exercise: guess expressions

For each of the following expressions, try to guess the result

<div class="alert alert-warning">

**WARNING: the following may cause severe convulsions and nausea.**

During clinical trials, both mathematically inclined and math-averse patients have experienced illness, for different reasons which are currently being investigated.

</div>

```python
a.  0.0 * -0.0
b.  (-0.0)**3
c.  np.log(-7) == math.log(-7)
d.  np.log(-7) == np.log(-7)
e.  np.isnan( 1 / np.log(1) )
f.  np.sqrt(-1) * np.sqrt(-1)   # sqrt = square root
g.  3 ** np.inf
h   3 ** -np.inf
i.  1/np.sqrt(-3)
j.  1/np.sqrt(-0.0)
m.  np.sqrt(np.inf) - np.sqrt(-np.inf)
n.  np.sqrt(np.inf) + ( 1 / np.sqrt(-0.0) )
o.  np.isneginf(np.log(np.e) / np.sqrt(-0.0))  
p.  np.isinf(np.log(np.e) / np.sqrt(-0.0))
q.  [np.nan, np.inf] == [np.nan, np.inf]
r.  [np.nan, -np.inf] == [np.nan, np.inf]
s.  [np.nan, np.inf] == [-np.nan, np.inf]
```

## Continue

Go on with [numpy exercises](https://en.softpython.org/matrices-numpy/matrices-numpy2-sol.html).